server:
  port: 0

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ms-products
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true

jwt:
  secret: sadfljhasdruywtqkjyfgsjfbagjksfajlsdgfjk
