server:
  port: 0

spring:
  application:
    name: ms-auth

jwt:
  secret: sadfljhasdruywtqkjyfgsjfbagjksfajlsdgfjk

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}